apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  istio:
    global:
      hub: quay.io/maistra
      tag: latest-qe
      imagePullPolicy: Always
     
      # the following lines enable tls across the control and data planes
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: true
 
      # enable multitenant
      multitenant: true
 
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
    istio_cni:
      enabled: true
 
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        # set to true to enable IOR
        ior_enabled: true
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
        type: ClusterIP
        ports:
        - port: 15020
          targetPort: 15020
          name: status-port
        - port: 80
          targetPort: 8080
          name: http2
        - port: 443
          name: https
          targetPort: 8443
          # This is the port where sni routing happens
        - port: 15443
          targetPort: 15443
          name: tls
        - port: 31400
          targetPort: 31400
          name: tcp
 
    mixer:
      policy:
        autoscaleEnabled: false
 
      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G
 
    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0
 
    kiali:
      imagePullPolicy: Always
      enabled: true
      dashboard:
        user: admin
        passphrase: admin
 
    tracing:
      # change to false to disable tracing (i.e. jaeger)
      enabled: true
      jaeger:
        # simple, all-in-one strategy
        #template: all-in-one
        # production strategy, utilizing elasticsearch
        template: production-elasticsearch
        # if required. only one instance may use agentStrategy=DaemonSet
        #agentStrategy: DaemonSet
        elasticsearch:
          nodeCount: 1
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"

---

apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  - test1
  - test2
  - test3
